# H2 Core URL Linkage using PostgreSQL Emulation Mode
spring.datasource.url=jdbc:h2:mem:pronurse_mock_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Management Panel Console URL Target
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Hibernate settings adjusted specifically for H2 Compatibility
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

jwt.secret=+O+lT01PYSxnXOMeI0qfYNyOR/eS4VWSlTNTLADH6DIWxBR5QCuuw0aMaNAMfaw8/Q7k5bBFjR9IFAca4Bth4Q==
