spring.datasource.url=jdbc:mysql://localhost:3306/pro-nurse-db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=pro_nurse_user
spring.datasource.password=Pro_Nurse_1234
spring.cloud.gcp.secretmanager.enabled=false
spring.cloud.gcp.core.enabled=false
spring.cloud.gcp.storage.enabled=false
spring.cloud.gcp.sql.enabled=false

jwt.secret=5qT+gYG7fAoYxvHRlzWVNz2aDhhrv4KmiGQLyCXT+FntX2sZnRMlPB6I0mfGR6vARuavxR3ANLRM3pi0Fn1oZ2x2xzClGoLcRCFDoZmXfsg=

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.flywaydb=DEBUG

# Local Mail (Optional)
spring.mail.host=smtp.zoho.in
spring.mail.port=465
spring.mail.username=noreply@desitechsolutions.com
spring.mail.password=MyDx3GTKQQnH
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.zoho.in
app.mail.display-name=VyaparSathi Support

# Timeouts (good practice)
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Debug (keep for now, remove later)
spring.mail.properties.mail.debug=true

# Local Frontend
app.reset-token-expiration=1800000
app.reset-password-url=
app.allowed-origins=

spring.file.upload.dir=static/uploads/
