spring.application.name=pro-nurse-backend-api
spring.profiles.active=local
server.port=${PORT:8080}

# JWT Token Configurations
jwt.expiration=${JWT_EXPIRATION:36000000}
jwt.refreshExpiration=604800000

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# Production-Scale File Upload Thresholds
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# Formatting Configs