-- Test Database Schema
-- This file is automatically loaded by Spring Boot for test database initialization

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile VARCHAR(15) UNIQUE NOT NULL,
    name VARCHAR(100),
    email VARCHAR(100),
    password_hash VARCHAR(255),
    role VARCHAR(20) NOT NULL,
    is_mobile_verified BOOLEAN DEFAULT FALSE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Patient profiles
CREATE TABLE IF NOT EXISTS patient_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR(50) UNIQUE NOT NULL,
    user_id BIGINT UNIQUE NOT NULL,
    gender VARCHAR(20),
    dob VARCHAR(20),
    blood_group VARCHAR(10),
    address TEXT,
    profile_image_path VARCHAR(255),
    chronic_diseases TEXT,
    medical_report_path VARCHAR(255),
    latitude DOUBLE,
    longitude DOUBLE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Nurse profiles
CREATE TABLE IF NOT EXISTS nurse_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nurse_id VARCHAR(50) UNIQUE NOT NULL,
    user_id BIGINT UNIQUE NOT NULL,
    gender VARCHAR(20),
    dob VARCHAR(20),
    address TEXT,
    qualification VARCHAR(100),
    experience VARCHAR(100),
    specialization VARCHAR(100),
    languages_spoken VARCHAR(255),
    latitude DOUBLE,
    longitude DOUBLE,
    profile_image_path VARCHAR(255),
    registration_number VARCHAR(100) UNIQUE,
    is_verified BOOLEAN DEFAULT FALSE,
    is_on_duty BOOLEAN DEFAULT FALSE,
    verification_status VARCHAR(30) DEFAULT 'Pending',
    reject_reason TEXT,
    verified_by VARCHAR(100),
    verified_date TIMESTAMP,
    average_rating DOUBLE DEFAULT 0.0,
    total_reviews_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Medical services catalog
CREATE TABLE IF NOT EXISTS medical_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    base_price DECIMAL(10,2) NOT NULL,
    estimated_duration_minutes INT,
    is_active BOOLEAN DEFAULT TRUE,
    parent_id BIGINT,
    FOREIGN KEY (parent_id) REFERENCES medical_services(id)
);

-- Bookings
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_no VARCHAR(50) UNIQUE NOT NULL,
    patient_user_id BIGINT NOT NULL,
    assigned_nurse_user_id BIGINT,
    booking_status VARCHAR(30),
    payment_status VARCHAR(30),
    booking_date DATE NOT NULL,
    booking_time VARCHAR(20) NOT NULL,
    remarks TEXT,
    latitude DOUBLE,
    longitude DOUBLE,
    raw_address TEXT NOT NULL,
    razorpay_order_id VARCHAR(100),
    razorpay_payment_id VARCHAR(100),
    razorpay_signature VARCHAR(255),
    prescription_file_path VARCHAR(255),
    is_emergency BOOLEAN DEFAULT FALSE,
    emergency_description TEXT,
    emergency_contact_name VARCHAR(100),
    emergency_contact_mobile VARCHAR(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_user_id) REFERENCES users(id),
    FOREIGN KEY (assigned_nurse_user_id) REFERENCES users(id)
);

-- Booking selected items
CREATE TABLE IF NOT EXISTS booking_selected_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    item_name VARCHAR(150) NOT NULL,
    price_charged DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    FOREIGN KEY (service_id) REFERENCES medical_services(id)
);

-- Booking assignments
CREATE TABLE IF NOT EXISTS booking_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    nurse_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    notified_at TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    FOREIGN KEY (nurse_user_id) REFERENCES users(id)
);

-- Nurse reviews
CREATE TABLE IF NOT EXISTS nurse_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    nurse_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    is_moderated BOOLEAN DEFAULT FALSE,
    moderation_status VARCHAR(20) DEFAULT 'PENDING',
    moderation_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES bookings(id),
    FOREIGN KEY (nurse_id) REFERENCES users(id),
    FOREIGN KEY (patient_id) REFERENCES users(id)
);

-- Nurse wallets
CREATE TABLE IF NOT EXISTS nurse_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nurse_user_id BIGINT UNIQUE NOT NULL,
    current_balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_earned DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    negative_limit DECIMAL(10,2) NOT NULL DEFAULT 500.00,
    is_suspended BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (nurse_user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Wallet transactions
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    gross_amount DECIMAL(10,2) NOT NULL,
    platform_fee DECIMAL(10,2) NOT NULL,
    net_earning DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (wallet_id) REFERENCES nurse_wallets(id) ON DELETE CASCADE,
    FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

-- Payout requests
CREATE TABLE IF NOT EXISTS payout_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    bank_account_number VARCHAR(50),
    ifsc_code VARCHAR(20),
    account_holder_name VARCHAR(100),
    processed_at TIMESTAMP,
    rejection_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (wallet_id) REFERENCES nurse_wallets(id) ON DELETE CASCADE
);

-- Refresh tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(500) UNIQUE NOT NULL,
    mobile VARCHAR(15) NOT NULL,
    expiry_date TIMESTAMP NOT NULL
);

-- Emergency contacts
CREATE TABLE IF NOT EXISTS emergency_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    contact_name VARCHAR(100) NOT NULL,
    contact_mobile VARCHAR(15) NOT NULL,
    relationship VARCHAR(50),
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Favorite nurses
CREATE TABLE IF NOT EXISTS favorite_nurses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    nurse_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (nurse_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (patient_id, nurse_id)
);

-- FCM tokens
CREATE TABLE IF NOT EXISTS fcm_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_token VARCHAR(500) UNIQUE NOT NULL,
    device_type VARCHAR(20),
    device_name VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    last_used_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Notification preferences
CREATE TABLE IF NOT EXISTS notification_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    booking_alerts BOOLEAN DEFAULT TRUE,
    payment_alerts BOOLEAN DEFAULT TRUE,
    review_alerts BOOLEAN DEFAULT TRUE,
    promotional_alerts BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);