-- ============================================================
-- V17: Nurse Onboarding Document Management System
-- ============================================================
-- Author: ProNurse Backend Team
-- Purpose: Introduce per-document tracking, review history audit trail,
--          and structured onboarding lifecycle status for nurses.
--
-- Changes:
--   1. Create nurse_documents table
--   2. Create document_review_history table
--   3. Add onboarding_status column to nurse_profiles
--   4. Backfill onboarding_status for existing nurse records
--
-- NOTE: All changes are additive. Existing APIs and data are unaffected.
-- ============================================================

-- 1. Create nurse_documents table
--    Each row represents one uploaded document file.
--    Versioning (version column) allows multiple submissions of the same
--    document type (e.g., when a nurse replaces a rejected PAN Card).
CREATE TABLE nurse_documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nurse_profile_id  BIGINT NOT NULL,
    document_type     VARCHAR(50) NOT NULL,
    document_status   VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    file_name         VARCHAR(500) NOT NULL,
    original_name     VARCHAR(255),
    file_size_bytes   BIGINT,
    mime_type         VARCHAR(100),
    version           INT NOT NULL DEFAULT 1,
    review_comment    TEXT,
    reviewed_by       VARCHAR(100),
    reviewed_at       TIMESTAMP WITHOUT TIME ZONE,
    uploaded_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_doc_nurse_profile
        FOREIGN KEY (nurse_profile_id) REFERENCES nurse_profiles(id) ON DELETE CASCADE,

    -- Ensures one active record per (nurse, documentType, version) combination
    CONSTRAINT uq_nurse_doc_type_version UNIQUE (nurse_profile_id, document_type, version)
);

CREATE INDEX idx_nurse_doc_profile ON nurse_documents(nurse_profile_id);
CREATE INDEX idx_nurse_doc_status  ON nurse_documents(document_status);
CREATE INDEX idx_nurse_doc_type    ON nurse_documents(document_type);

-- 2. Create document_review_history table
--    Append-only audit log for all document lifecycle events.
--    Never updated — only inserted.
CREATE TABLE document_review_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id      BIGINT NOT NULL,
    nurse_profile_id BIGINT NOT NULL,
    action           VARCHAR(30) NOT NULL,
    comment          TEXT,
    performed_by     VARCHAR(100) NOT NULL,
    performed_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_review_hist_doc
        FOREIGN KEY (document_id) REFERENCES nurse_documents(id) ON DELETE CASCADE
);

CREATE INDEX idx_doc_review_hist_doc     ON document_review_history(document_id);
CREATE INDEX idx_doc_review_hist_profile ON document_review_history(nurse_profile_id);
CREATE INDEX idx_doc_review_hist_action  ON document_review_history(action);

-- 3. Add onboarding_status column to nurse_profiles
--    Defaults to 'DRAFT' for all new and existing nurses.
ALTER TABLE nurse_profiles
    ADD COLUMN IF NOT EXISTS onboarding_status VARCHAR(50) DEFAULT 'DRAFT';

-- 4. Backfill: nurses with is_verified = TRUE had already been approved
--    before this feature existed. Mark them as ONBOARDING_COMPLETED so
--    they are not incorrectly treated as pending.
UPDATE nurse_profiles
   SET onboarding_status = 'ONBOARDING_COMPLETED'
 WHERE is_verified = TRUE
   AND verification_status = 'Approved';

-- All other nurses retain the default 'DRAFT' status (already set by column default).
