-- 1. Create Users Core Identity Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mobile VARCHAR(15) UNIQUE NOT NULL,
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_mobile ON users(mobile);

-- 2. Create Refresh Tokens Table for Session Management
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) UNIQUE NOT NULL,
    mobile VARCHAR(15) NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Nurse Profiles Sub-Domain Table
CREATE TABLE nurse_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nurse_id VARCHAR(50) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    gender VARCHAR(10),
    dob VARCHAR(20),
    address TEXT,
    qualification VARCHAR(100),
    experience VARCHAR(50),
    specialization VARCHAR(100),
    languages_spoken VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    profile_image_path VARCHAR(255),
    registration_number VARCHAR(100) UNIQUE,
    is_verified BOOLEAN DEFAULT FALSE,
    is_on_duty BOOLEAN DEFAULT FALSE,
    verification_status VARCHAR(30) DEFAULT 'Pending',
    reject_reason TEXT,
    verified_by VARCHAR(100),
    verified_date TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_nurse_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. Create Patient Profiles Sub-Domain Table
CREATE TABLE patient_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR(50) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    gender VARCHAR(10),
    dob VARCHAR(20),
    blood_group VARCHAR(10),
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    profile_image_path VARCHAR(255),
    chronic_diseases TEXT,
    medical_report_path VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_patient_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);