-- Ensure PostGIS spatial tracking is initialized when migrating onto real PostgreSQL instances
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Master Service / Sub-Service Hierarchy Table
CREATE TABLE medical_services (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  parent_id BIGINT, -- If NULL, this is a top-level category like "Home Nursing"
                                  name VARCHAR(150) NOT NULL,
                                  description TEXT,
                                  base_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
                                  estimated_duration_minutes INT DEFAULT 30,
                                  is_active BOOLEAN DEFAULT TRUE,
                                  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                                  CONSTRAINT fk_service_parent FOREIGN KEY (parent_id) REFERENCES medical_services(id) ON DELETE CASCADE
);

CREATE INDEX idx_services_parent ON medical_services(parent_id);

-- 2. Core Bookings Head Record Ledger Table (Contains Status, Dates, and Patient Coordinates)
CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          booking_no VARCHAR(50) UNIQUE NOT NULL,
                          patient_user_id BIGINT NOT NULL,
                          assigned_nurse_user_id BIGINT,
                          booking_status VARCHAR(30) DEFAULT 'PENDING', -- 'PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED'
                          payment_status VARCHAR(30) DEFAULT 'PENDING', -- 'PENDING', 'PAID'
                          booking_date DATE NOT NULL,
                          booking_time VARCHAR(20) NOT NULL,
                          remarks TEXT,
                          latitude DOUBLE PRECISION NOT NULL,   -- Matches Booking.java primitive field
                          longitude DOUBLE PRECISION NOT NULL,  -- Matches Booking.java primitive field
                          raw_address TEXT NOT NULL,            -- Matches Booking.java primitive field
                          created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_booking_patient FOREIGN KEY (patient_user_id) REFERENCES users(id),
                          CONSTRAINT fk_booking_nurse FOREIGN KEY (assigned_nurse_user_id) REFERENCES users(id)
);

CREATE INDEX idx_bookings_status ON bookings(booking_status);

-- 3. Line Items Mapping (Supports Booking Multiple Services at Once)
CREATE TABLE booking_selected_items (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        booking_id BIGINT NOT NULL,
                                        service_id BIGINT NOT NULL,
                                        item_name VARCHAR(150) NOT NULL,
                                        price_charged NUMERIC(10, 2) NOT NULL,

                                        CONSTRAINT fk_item_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
                                        CONSTRAINT fk_item_service FOREIGN KEY (service_id) REFERENCES medical_services(id)
);

-- 4. Chained Fan-Out Dispatch Tracker Table to Handle the Expiry Loop
CREATE TABLE booking_assignments (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     booking_id BIGINT NOT NULL,
                                     nurse_user_id BIGINT NOT NULL,
                                     status VARCHAR(20) NOT NULL DEFAULT 'RINGING', -- 'RINGING', 'ACCEPTED', 'REJECTED', 'TIMEOUT'
                                     notified_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                     expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                                     CONSTRAINT uk_booking_nurse_assignment UNIQUE (booking_id, nurse_user_id),
                                     CONSTRAINT fk_assignment_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
                                     CONSTRAINT fk_assignment_nurse FOREIGN KEY (nurse_user_id) REFERENCES users(id)
);

CREATE INDEX idx_assignment_expiry_lookup ON booking_assignments(expires_at, status);

-- Seed Baseline Service Items for Testing
INSERT INTO medical_services (id, parent_id, name, description, base_price) VALUES
                                                                                (1, NULL, 'Home Nursing', 'Professional nursing care at your doorstep', 0.00),
                                                                                (2, 1, 'Injection Administration', 'IV/IM Injection service', 350.00),
                                                                                (3, 1, 'Wound Dressing', 'Sterile dressing changes for wounds', 500.00),
                                                                                (4, 1, 'Blood Pressure Check', 'Regular BP vital check monitoring', 150.00);