-- 1. Create Master Review and Ratings Analytics Table
CREATE TABLE nurse_reviews (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               booking_id BIGINT NOT NULL UNIQUE,
                               patient_user_id BIGINT NOT NULL,
                               nurse_user_id BIGINT NOT NULL,
                               rating_score INT NOT NULL CHECK (rating_score BETWEEN 1 AND 5),
                               review_text TEXT,
                               created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_review_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
                               CONSTRAINT fk_review_patient FOREIGN KEY (patient_user_id) REFERENCES users(id),
                               CONSTRAINT fk_review_nurse FOREIGN KEY (nurse_user_id) REFERENCES users(id)
);

CREATE INDEX idx_review_nurse_target ON nurse_reviews(nurse_user_id);

-- 2. Add Cached Rating Fields to Nurse Profiles for Blistering Performance
ALTER TABLE nurse_profiles ADD COLUMN IF NOT EXISTS average_rating NUMERIC(3, 2) DEFAULT 0.00;
ALTER TABLE nurse_profiles ADD COLUMN IF NOT EXISTS total_reviews_count INT DEFAULT 0;