-- 1. Create Nurse Wallet Master Balances Table
CREATE TABLE nurse_wallets (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               nurse_user_id BIGINT NOT NULL UNIQUE,
                               current_balance NUMERIC(12, 2) DEFAULT 0.00,
                               total_earned NUMERIC(12, 2) DEFAULT 0.00,
                               updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_wallet_nurse FOREIGN KEY (nurse_user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 2. Create Wallet Ledger Transaction Histories Table
CREATE TABLE wallet_transactions (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     wallet_id BIGINT NOT NULL,
                                     booking_id BIGINT NOT NULL,
                                     transaction_type VARCHAR(20) NOT NULL, -- 'CREDIT' (earnings), 'DEBIT' (payouts)
                                     gross_amount NUMERIC(10, 2) NOT NULL,    -- Total patient paid (e.g., 1000.00)
                                     platform_fee NUMERIC(10, 2) NOT NULL,    -- Platform Cut (e.g., 100.00)
                                     net_earning NUMERIC(10, 2) NOT NULL,     -- Staff portion credited (e.g., 900.00)
                                     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_tx_wallet FOREIGN KEY (wallet_id) REFERENCES nurse_wallets(id) ON DELETE CASCADE,
                                     CONSTRAINT fk_tx_booking FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

CREATE INDEX idx_wallet_tx_history ON wallet_transactions(wallet_id);